# Пользователи

## Регистрация пользователя
POST http://localhost:1234/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Dima",
  "email": "dima@test.ru",
  "avatar": "avatar.png",
  "password": "qwerty123"
}

###

## Авторизация пользователя - WIP!!!
POST http://localhost:1234/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "dima@test.ru",
  "password": "qwerty123"
}

###

## Проверка статуса авторизации пользователя - WIP!!!
GET http://localhost:1234/users/login HTTP/1.1
Content-Type: application/json

###

## Загрузка аватарки пользователя - WIP!!!

POST http://localhost:1234/users/63dd6c54b2a7ff5536fe7b95/avatar HTTP/1.1

###
