# Фильмы

## Получить список фильмов
GET http://localhost:1234/movies/?count=2 HTTP/1.1
Content-Type: application/json

###

## Добавить новый фильм
POST http://localhost:1234/movies HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

{
  "title": "Список Шиндлера - test 6",
  "description": "Фильм рассказывает реальную историю загадочного Оскара Шиндлера, члена нацистской партии, преуспевающего фабриканта, спасшего во время Второй мировой войны почти 1200 евреев.",
  "postDate": "2022-11-06T12:36:07.872Z",
  "genre": "drama",
  "releaseYear": 1993,
  "previewFilePath": "https://preview/schindlers_list.mp4",
  "movieFilePath": "https://schindlers_list.mp4",
  "actors": [
    "Лиам Нисон",
    "Бен Кингсли",
    "Рэйф Файнс"
  ],
  "director": "Стивен Спилберг",
  "durationInMinutes": 132,
  "userId": "63f428f918205c386b8e3c58",
  "posterFilePath": "https://poster.jpg",
  "backgroundImageFilePath": "https://bg.jpg",
  "backgroundColor": "#AAAAAA"
}

###

## Получить список фильмов по жанру
GET http://localhost:1234/movies/?genre=comedy HTTP/1.1
Content-Type: application/json

###

## Получить список промо фильмов
GET http://localhost:1234/movies/lists/promo HTTP/1.1
Content-Type: application/json

###

## Получить информацию о фильме
GET http://localhost:1234/movies/63fa1a4b04734d999e97ddbd HTTP/1.1
Content-Type: application/json

###

## Удалить фильм
DELETE http://localhost:1234/movies/63fa1a4b04734d999e97ddbd HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

###

## Изменить данные фильма
PATCH http://localhost:1234/movies/63fa72d262831b8d8af894d2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

{
  "title": "Список Шиндлера - update 7",
  "description": "Фильм рассказывает реальную историю загадочного Оскара Шиндлера, члена нацистской партии, преуспевающего фабриканта, спасшего во время Второй мировой войны почти 1200 евреев.",
  "postDate": "2022-11-06T12:36:07.872Z",
  "genre": "drama",
  "releaseYear": 1993,
  "previewFilePath": "https://preview/schindlers_list.mp4",
  "movieFilePath": "https://schindlers_list.mp4",
  "actors": [
    "Лиам Нисон",
    "Бен Кингсли",
    "Рэйф Файнс"
  ],
  "director": "Стивен Спилберг",
  "durationInMinutes": 132,
  "userId": "63e32d642fad37c5ba8c34f8",
  "posterFilePath": "https://poster.jpg",
  "backgroundImageFilePath": "https://bg.jpg",
  "backgroundColor": "#9A9A9A",
  "isPromo": true
}

###

## Добавить 1 фильм в список "К просмотру"
POST http://localhost:1234/movies/watchlist/63fa72d262831b8d8af894d2/true HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

###

## Добавить 2 фильм в список "К просмотру"
POST http://localhost:1234/movies/watchlist/63f428f918205c386b8e3c55/true HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

###

## Удилаить 1 фильм из списка "К просмотру"
POST http://localhost:1234/movies/watchlist/63fa72d262831b8d8af894d2/false HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk

###

## Удилаить 2 фильм из списка "К просмотру"
POST http://localhost:1234/movies/watchlist/63f428f918205c386b8e3c55/false HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImRpbWFAdGVzdDIucnUiLCJpZCI6IjYzZmJhMzBlY2Q1YjhhMWY2YTk0N2QzMCIsImlhdCI6MTY3NzQzNTY3NywiZXhwIjoxNjc3NjA4NDc3fQ.yEVmqe08wsX5bYdNFJ-Fa1kO4dor9bA6PIwrtCg2lmk
